## Julia 的语法很类似于 Matlab

In [1]:
v1 = [1, 3, 4, 9, 13]

5-element Array{Int64,1}:
  1
  3
  4
  9
 13

In [5]:
# 对元素赋值将在原地修改元素的值，如
v1[2] = -999; v1

5-element Array{Int64,1}:
    1
 -999
    4
    9
   13

In [7]:
v1 = [1, 3, 4, 9, 13] 
v3 = [2, 5, 6, 7, 10] 
v1 .+ v3

5-element Array{Int64,1}:
  3
  8
 10
 16
 23

In [8]:
zeros(5)

5-element Array{Float64,1}:
 0.0
 0.0
 0.0
 0.0
 0.0

In [9]:
Vector{Float64}(5)

MethodError: MethodError: no method matching Array{Float64,1}(::Int64)
Closest candidates are:
  Array{Float64,1}() where T at boot.jl:424
  Array{Float64,1}(!Matched::UndefInitializer, !Matched::Int64) where T at boot.jl:405
  Array{Float64,1}(!Matched::UndefInitializer, !Matched::Int64...) where {T, N} at boot.jl:411
  ...

In [10]:
for i in eachindex(v1) 
    println("v1[", i, "] = ", v1[i]) 
end

v1[1] = 1
v1[2] = 3
v1[3] = 4
v1[4] = 9
v1[5] = 13


In [12]:
A1 = [1 2 3 
    4 5 6]

2×3 Array{Int64,2}:
 1  2  3
 4  5  6

In [13]:
A1[1:2,2:3]

2×2 Array{Int64,2}:
 2  3
 5  6

In [14]:
for j = 1:size(A1,2), i = 1:size(A1,1) 
    println("A1[", i, ", ", j, "] = ", A1[i, j]) 
end

A1[1, 1] = 1
A1[2, 1] = 4
A1[1, 2] = 2
A1[2, 2] = 5
A1[1, 3] = 3
A1[2, 3] = 6


In [15]:
for i in eachindex(A1) println("A1[", i, "] = ", A1[i]) 
end

A1[1] = 1
A1[2] = 4
A1[3] = 2
A1[4] = 5
A1[5] = 3
A1[6] = 6


In [16]:
A1 .+ 100

2×3 Array{Int64,2}:
 101  102  103
 104  105  106

In [17]:
A3 = [11 12; 21 22]

2×2 Array{Int64,2}:
 11  12
 21  22

In [18]:
A3 * [1, -1]

2-element Array{Int64,1}:
 -1
 -1

In [20]:
[1,-1] * [1 -1]

2×2 Array{Int64,2}:
  1  -1
 -1   1

In [21]:
[1 -1] * [1,-1]

1-element Array{Int64,1}:
 2

In [22]:
A4 = [1 3; 3 1]
A4'

2×2 LinearAlgebra.Adjoint{Int64,Array{Int64,2}}:
 1  3
 3  1

In [24]:
A4 \ [-2, 2]

2-element Array{Float64,1}:
  1.0
 -1.0

In [26]:
function mysd(x) #计算样本标准差
    n = length(x) 
    mx = 0.0 
    for z in x 
        mx += z
        end 
        mx /= n 
        s = 0.0 
        for z in x 
            s += (z - mx)^2 
        end 
    sqrt(s / (n-1)) 
end

mysd (generic function with 1 method)

In [27]:
mysd([1, 2, 3, 4, 5])

1.5811388300841898

In [28]:
function mysd_simple(x) 
    n = length(x) 
    mx = sum(x)/n 
    sqrt( sum(x .- mx) / (n-1) ) 
end

mysd_simple (generic function with 1 method)

第二个版本只是利用了向量化和已有函数，在 Julia 中其运行效率并不比第一个版本更好，甚至于不如第一个版本。**Julia 语言与 R、Matlab 等语言不同，显式的循环一般有更高的执行效率，向量化写法仅仅是可以使得程序比较简洁。**

用 begin ... end可以将多行的多个表达式组合起来当作一个表达式，复合表达式的值是其中最后一个表达式的值。

In [30]:
z = begin
    x = 1
    y = 2
    x + y
end
z

3

&& 是一种短路运算，表达式 cond && expr 仅当 cond为 true 时才计算（运行）expr，所以这种写法经常用作程序分支的简写：条件 cond为真时执行 expr，否则不执行。

In [32]:
x = -1.44 
x < 0 && println(" 平方根计算：自变量定义域错误，x=", x)

 平方根计算：自变量定义域错误，x=-1.44


In [33]:
x < 0 || (y = sqrt(x))

true

## Julia

In [34]:
println("There is more than one way to say hello:") 

There is more than one way to say hello:


In [35]:
helloArray = ["Hello","G’day","Shalom"] 
for i in 1:3  
    println("\t", helloArray[i], " World!") 
end

	Hello World!
	G’day World!
	Shalom World!


In [36]:
println("\nThese squares are just perfect:")


These squares are just perfect:


In [37]:
squares = [i^2 for i in 0:10]

11-element Array{Int64,1}:
   0
   1
   4
   9
  16
  25
  36
  49
  64
  81
 100

In [39]:
for s in squares 
    print(" ",s) 
end

 0 1 4 9 16 25 36 49 64 81 100

In [41]:
sqrt.(squares)

11-element Array{Float64,1}:
  0.0
  1.0
  2.0
  3.0
  4.0
  5.0
  6.0
  7.0
  8.0
  9.0
 10.0

In [42]:
array1 = [(2n+1)^2 for n in 1:5]

5-element Array{Int64,1}:
   9
  25
  49
  81
 121

In [43]:
array2 = [sqrt(i) for i in array1]

5-element Array{Float64,1}:
  3.0
  5.0
  7.0
  9.0
 11.0

In [44]:
println(typeof(1:5), " ", typeof(array1), " ", typeof(array2))

UnitRange{Int64} Array{Int64,1} Array{Float64,1}


In [45]:
1:5, array1, array2 # 元组？？！

(1:5, [9, 25, 49, 81, 121], [3.0, 5.0, 7.0, 9.0, 11.0])

In [47]:
x=rand(8); # 分号屏蔽结果

In [48]:
x 

8-element Array{Float64,1}:
 0.8809476402464129
 0.5830104252208124
 0.5099831460374844
 0.4640657094024694
 0.41971906794897484
 0.9238731621367917
 0.4565324444934198
 0.20779791602591646

### Help

In [49]:
?sqrt

search: sqrt isqrt squares



```
sqrt(x)
```

Return $\sqrt{x}$. Throws [`DomainError`](@ref) for negative [`Real`](@ref) arguments. Use complex negative arguments instead. The prefix operator `√` is equivalent to `sqrt`.

# Examples

```jldoctest; filter = r"Stacktrace:(\n \[[0-9]+\].*)*"
julia> sqrt(big(81))
9.0

julia> sqrt(big(-81))
ERROR: DomainError with -81.0:
NaN result for non-NaN input.
Stacktrace:
 [1] sqrt(::BigFloat) at ./mpfr.jl:501
[...]

julia> sqrt(big(complex(-81)))
0.0 + 9.0im
```

---

```
sqrt(A::AbstractMatrix)
```

If `A` has no negative real eigenvalues, compute the principal matrix square root of `A`, that is the unique matrix $X$ with eigenvalues having positive real part such that $X^2 = A$. Otherwise, a nonprincipal square root is returned.

If `A` is symmetric or Hermitian, its eigendecomposition ([`eigen`](@ref)) is used to compute the square root. Otherwise, the square root is determined by means of the Björck-Hammarling method [^BH83], which computes the complex Schur form ([`schur`](@ref)) and then the complex square root of the triangular factor.

[^BH83]: Åke Björck and Sven Hammarling, "A Schur method for the square root of a matrix", Linear Algebra and its Applications, 52-53, 1983, 127-140. [doi:10.1016/0024-3795(83)80010-X](https://doi.org/10.1016/0024-3795(83)80010-X)

# Examples

```jldoctest
julia> A = [4 0; 0 4]
2×2 Array{Int64,2}:
 4  0
 0  4

julia> sqrt(A)
2×2 Array{Float64,2}:
 2.0  0.0
 0.0  2.0
```


In [50]:
methods(sqrt)#different Julia methods implementation for the function sqrt()

# 19 methods for generic function "sqrt":
[1] sqrt(a::Float16) in Base.Math at math.jl:1114
[2] sqrt(a::Complex{Float16}) in Base.Math at math.jl:1115
[3] sqrt(::Missing) in Base.Math at math.jl:1167
[4] sqrt(x::BigFloat) in Base.MPFR at mpfr.jl:581
[5] sqrt(x::BigInt) in Base.MPFR at mpfr.jl:588
[6] sqrt(z::Complex{#s69} where #s69<:AbstractFloat) in Base at complex.jl:482
[7] sqrt(z::Complex) in Base at complex.jl:506
[8] sqrt(x::Union{Float32, Float64}) in Base.Math at math.jl:557
[9] sqrt(x::Real) in Base.Math at math.jl:583
[10] sqrt(A::Union{DenseArray{#s662,2}, Base.ReinterpretArray{#s662,2,S,A} where S where A<:Union{SubArray{T,N,A,I,true} where I<:Union{Tuple{Vararg{Real,N} where N}, Tuple{AbstractUnitRange,Vararg{Any,N} where N}} where A<:DenseArray where N where T, DenseArray}, Base.ReshapedArray{#s662,2,A,MI} where MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N} where N} where A<:Union{Base.ReinterpretArray{T,N,S,A} where S where A<:Union{SubArray{T,N,A,I,true} where I<:Union{Tuple{Vararg{Real,N} where N}, Tuple{AbstractUnitRange,Vararg{Any,N} where N}} where A<:DenseArray where N where T, DenseArray} where N where T, SubArray{T,N,A,I,true} where I<:Union{Tuple{Vararg{Real,N} where N}, Tuple{AbstractUnitRange,Vararg{Any,N} where N}} where A<:DenseArray where N where T, DenseArray}, SubArray{#s662,2,A,I,L} where L where I<:Tuple{Vararg{Union{Int64, AbstractRange{Int64}, Base.AbstractCartesianIndex},N} where N} where A<:Union{Base.ReinterpretArray{T,N,S,A} where S where A<:Union{SubArray{T,N,A,I,true} where I<:Union{Tuple{Vararg{Real,N} where N}, Tuple{AbstractUnitRange,Vararg{Any,N} where N}} where A<:DenseArray where N where T, DenseArray} where N where T, Base.ReshapedArray{T,N,A,MI} where MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N} where N} where A<:Union{Base.ReinterpretArray{T,N,S,A} where S where A<:Union{SubArray{T,N,A,I,true} where I<:Union{Tuple{Vararg{Real,N} where N}, Tuple{AbstractUnitRange,Vararg{Any,N} where N}} where A<:DenseArray where N where T, DenseArray} where N where T, SubArray{T,N,A,I,true} where I<:Union{Tuple{Vararg{Real,N} where N}, Tuple{AbstractUnitRange,Vararg{Any,N} where N}} where A<:DenseArray where N where T, DenseArray} where N where T, DenseArray}} where #s662<:Real) in LinearAlgebra at /Applications/Julia-1.4.app/Contents/Resources/julia/share/julia/stdlib/v1.4/LinearAlgebra/src/dense.jl:734
[11] sqrt(A::Union{DenseArray{#s662,2}, Base.ReinterpretArray{#s662,2,S,A} where S where A<:Union{SubArray{T,N,A,I,true} where I<:Union{Tuple{Vararg{Real,N} where N}, Tuple{AbstractUnitRange,Vararg{Any,N} where N}} where A<:DenseArray where N where T, DenseArray}, Base.ReshapedArray{#s662,2,A,MI} where MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N} where N} where A<:Union{Base.ReinterpretArray{T,N,S,A} where S where A<:Union{SubArray{T,N,A,I,true} where I<:Union{Tuple{Vararg{Real,N} where N}, Tuple{AbstractUnitRange,Vararg{Any,N} where N}} where A<:DenseArray where N where T, DenseArray} where N where T, SubArray{T,N,A,I,true} where I<:Union{Tuple{Vararg{Real,N} where N}, Tuple{AbstractUnitRange,Vararg{Any,N} where N}} where A<:DenseArray where N where T, DenseArray}, SubArray{#s662,2,A,I,L} where L where I<:Tuple{Vararg{Union{Int64, AbstractRange{Int64}, Base.AbstractCartesianIndex},N} where N} where A<:Union{Base.ReinterpretArray{T,N,S,A} where S where A<:Union{SubArray{T,N,A,I,true} where I<:Union{Tuple{Vararg{Real,N} where N}, Tuple{AbstractUnitRange,Vararg{Any,N} where N}} where A<:DenseArray where N where T, DenseArray} where N where T, Base.ReshapedArray{T,N,A,MI} where MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N} where N} where A<:Union{Base.ReinterpretArray{T,N,S,A} where S where A<:Union{SubArray{T,N,A,I,true} where I<:Union{Tuple{Vararg{Real,N} where N}, Tuple{AbstractUnitRange,Vararg{Any,N} where N}} where A<:DenseArray where N where T,

### @Time 

In [53]:
using Statistics
@time begin
    data = Float64[]
        for _ in 1:10^6
            group = Float64[]
                for _ in 1:5*10^2
                    push!(group,rand())
                end 
            push!(data,mean(group))
        end 
    println("98% of the means lie in the estimated range: ",(quantile(data,0.01),quantile(data,0.99)) ) 
end

98% of the means lie in the estimated range: (0.4700385860036091, 0.5300328640468939)
 11.595299 seconds (10.28 M allocations: 7.988 GiB, 13.99% gc time)


In [ ]:
import Pkg; Pkg.add("Statistics")

In [55]:
using Statistics

@time begin

data = [mean(rand(5*10^2)) for _ in 1:10^6] 
    println("98% of the means lie in the estimated range: ", (quantile(data,0.01),quantile(data,0.99)) )

end

98% of the means lie in the estimated range: (0.4699070465210751, 0.5299989674082936)
  2.622215 seconds (1.05 M allocations: 3.899 GiB, 36.33% gc time)


### Bubble Sort

the bubble sort algorithm is not the most efficient sorting algorithm, but is introduced here as a means of understanding Julia better. 

In [64]:
data = [65, 51, 32, 12, 23, 84, 68.0, 1]

8-element Array{Float64,1}:
 65.0
 51.0
 32.0
 12.0
 23.0
 84.0
 68.0
  1.0

In [61]:
function BubbleSort!(a)
    n=length(a)
    for i in 1:n-1
        for j in 1:n-i 
            if a[j]>a[j+1]
                a[j],a[j+1]=a[j+1],a[j]
            end
        end
    end
    return a
end

BubbleSort! (generic function with 1 method)

In [65]:
BubbleSort!(data)

8-element Array{Float64,1}:
  1.0
 12.0
 23.0
 32.0
 51.0
 65.0
 68.0
 84.0

In [66]:
typeof(data)

Array{Float64,1}

### Roots of a Polynomial

In [6]:
using Roots
function polynomialGenerator(a...)
    n = length(a)-1
    poly = function(x)
        return sum([a[i+1]*x^i for i in 0:n])
        end
    return poly
end

polynomialGenerator (generic function with 1 method)

In [7]:
polynomial = polynomialGenerator(1,3,-10)

#7 (generic function with 1 method)

In [8]:
zeroVals = find_zeros(polynomial,-10,10)

2-element Array{Float64,1}:
 -0.19999999999999998
  0.5

In [9]:
println("Zeros of the function f(x): ", zeroVals)

Zeros of the function f(x): [-0.19999999999999998, 0.5]


In [13]:
using LinearAlgebra, StatsBase 
# Transition probability matrix 
P = [0.5 0.4 0.1; 0.3 0.2 0.5; 0.5 0.3 0.2] 
# First way 
piProb1 = (P^100)[1,:] 
# Second way 
A = vcat((P' - I)[1:2,:],ones(3)') 
b = [0 0 1]'
piProb2 = A\b 
# Third way 
eigVecs = eigvecs(copy(P')) 
highestVec = eigVecs[:,findmax(abs.(eigvals(P)))[2]] 
piProb3 = Array{Float64}(highestVec)/norm(highestVec,1) 
# Fourth way 
numInState = zeros(Int,3) 
state = 1 
N = 10^6 
for t in 1:N 
    numInState[state] += 1 
    global state = sample(1:3,weights(P[state,:])) 
end 
piProb4 = numInState/N 
[piProb1 piProb2 piProb3 piProb4]

3×4 Array{Float64,2}:
 0.4375  0.4375  0.4375  0.438218
 0.3125  0.3125  0.3125  0.31226
 0.25    0.25    0.25    0.249522

In [19]:
using HTTP, JSON 
data = HTTP.request("GET","https://ocw.mit.edu/ans7870/6/6.006/s08/lecturenotes/files/t8.shakespeare.txt") 
shakespeare = String(data.body) 
shakespeareWords = split(shakespeare)
jsonWords = HTTP.request("GET","https://raw.githubusercontent.com/"* 
    "h-Klok/StatsWithJuliaBook/master/1_chapter/jsonCode.json") 
parsedJsonDict = JSON.parse( String(jsonWords.body))
keywords = Array{String}(parsedJsonDict["words"]) 
numberToShow = parsedJsonDict["numToShow"] 
wordCount = Dict([(x,count(w -> lowercase(w) == lowercase(x), shakespeareWords)) 
        for x in keywords])
sortedWordCount = sort(collect(wordCount),by=last,rev=true) 
sortedWordCount[1:numberToShow]

HTTP.IOExtras.IOError: IOError(Base.IOError("connect: connection refused (ECONNREFUSED)", -61) during request(https://raw.githubusercontent.com/h-Klok/StatsWithJuliaBook/master/1_chapter/jsonCode.json))


### HTTP.request from the HTTP package is used to make a HTTP request

In [20]:
using Plots, LaTeXStrings, Measures; pyplot() 
f(x,y) = x^2 + y^2 
f0(x) = f(x,0) 
f2(x) = f(x,2) 
xVals, yVals = -5:0.1:5 , -5:0.1:5 
plot(xVals, [f0.(xVals), f2.(xVals)], 
    c=[:blue :red], xlims=(-5,5), legend=:top, 
    ylims=(-5,25), ylabel=L"f(x,\cdot)", label=[L"f(x,0)" L"f(x,2)"]) 
p1 = annotate!(0, -0.2, text("(0,0) The minimum\n of f(x,0)", :left, :top, 10)) 
z = [ f(x,y) for y in yVals, x in xVals ] 
p2 = surface(xVals, yVals, z, c=cgrad([:blue, :red]),legend=:none, 15 ylabel="y", zlabel=L"f(x,y)") 
M = z[1:10,1:10] 18 p3 = heatmap(M, c=cgrad([:blue, :red]), yflip=true, ylabel="y", 
    xticks=([1:10;], xVals), yticks=([1:10;], yVals)) 
plot(p1, p2, p3, layout=(1,3), size=(1200,400), xlabel="x", margin=5mm)

ArgumentError: ArgumentError: Package Plots not found in current path:
- Run `import Pkg; Pkg.add("Plots")` to install the Plots package.


### Creating Animations